global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'flink'
    static_configs:
      - targets: ['docker.for.mac.localhost:9250', 'docker.for.mac.localhost:9251',
                  'docker.for.mac.localhost:9252', 'docker.for.mac.localhost:9253',
                  'docker.for.mac.localhost:9254', 'docker.for.mac.localhost:9255',
                  'docker.for.mac.localhost:9256', 'docker.for.mac.localhost:9257',
                  'docker.for.mac.localhost:9258', 'docker.for.mac.localhost:9259',
                  'docker.for.mac.localhost:9260']